# -*- coding: utf-8 -*-
"""CIFAR-10 Image detection using cnn.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKqqFDAOzmJTxJGDuMnUiycBh3ATFkpv
"""

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
import matplotlib.pyplot as plt
import numpy as np

print("Loading CIFAR-10 dataset...")
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

X_train = X_train / 255.0
X_test  = X_test  / 255.0

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

l2_penalty = 0.0005

model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), padding='same',
                        kernel_regularizer=regularizers.l2(l2_penalty),
                        input_shape=(32, 32, 3)))
model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))

model.add(layers.Conv2D(32, (3, 3), padding='same',
                        kernel_regularizer=regularizers.l2(l2_penalty)))
model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))

model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.SpatialDropout2D(0.2))

model.add(layers.Conv2D(64, (3, 3), padding='same',
                        kernel_regularizer=regularizers.l2(l2_penalty)))
model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))

model.add(layers.Conv2D(64, (3, 3), padding='same',
                        kernel_regularizer=regularizers.l2(l2_penalty)))
model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))

model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.SpatialDropout2D(0.3))

model.add(layers.Flatten())
model.add(layers.Dense(256, kernel_regularizer=regularizers.l2(l2_penalty)))
model.add(layers.BatchNormalization())
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(10, activation='softmax'))

model.summary()

def custom_cross_entropy(y_true, y_pred):
    y_true_one_hot = tf.one_hot(tf.cast(tf.squeeze(y_true), tf.int32), depth=10)
    y_pred = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
    loss = -tf.reduce_mean(tf.reduce_sum(y_true_one_hot * tf.math.log(y_pred), axis=-1))
    return loss

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=custom_cross_entropy,
    metrics=['accuracy']
)

NUM_EPOCHS = 10

print(f"\nTraining for {NUM_EPOCHS} epochs...")
history = model.fit(
    X_train, y_train,
    epochs=NUM_EPOCHS,
    batch_size=128,
    validation_split=0.15
)

print("\nRunning evaluation on test set...")
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f"\nTest Accuracy: {test_acc * 100:.2f}%")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy', color='purple')
plt.plot(history.history['val_accuracy'], label='Val Accuracy', color='teal')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss', color='purple')
plt.plot(history.history['val_loss'], label='Val Loss', color='teal')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

plt.tight_layout()
plt.show()

# this cell uses model, X_test, y_test, class_names, np, plt from above cells
sample_idx = np.random.randint(0, len(X_test))
sample_img = X_test[sample_idx]
true_lbl   = int(y_test[sample_idx])

pred     = model.predict(np.expand_dims(sample_img, axis=0))
pred_lbl = np.argmax(pred)

plt.figure(figsize=(3, 3))
plt.imshow(sample_img)
plt.title(f"True: {class_names[true_lbl]}\nPred: {class_names[pred_lbl]}")
plt.axis('off')
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# getting predictions for the full test set
print("Generating predictions on test set...")
y_pred_probs = model.predict(X_test)
y_pred       = np.argmax(y_pred_probs, axis=1)
y_true       = y_test.flatten()  # flatten from (10000,1) to (10000,)

# 1. overall metrics summary
print("\n========== MODEL PERFORMANCE SUMMARY ==========")
print(f"  Test Loss     : {test_loss:.4f}")
print(f"  Test Accuracy : {test_acc * 100:.2f}%")
print("================================================\n")

# 2. per-class precision, recall and f1-score
print("Per-Class Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

# 3. confusion matrix heatmap
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.show()

# 4. per-class accuracy printed clearly
print("\nPer-Class Accuracy:")
for i, cls in enumerate(class_names):
    class_acc = cm[i, i] / cm[i].sum() * 100
    print(f"  {cls:<12}: {class_acc:.2f}%")